//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/_Scripts/General/Input/InputMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMaster : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMaster"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""e053d83d-8535-4868-a630-72c397b5d7c3"",
            ""actions"": [
                {
                    ""name"": ""ArrowMovement"",
                    ""type"": ""Button"",
                    ""id"": ""70892e3d-250f-4237-a502-b1321820c988"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftMouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""6a73f7fa-bf06-4d7e-ac53-fa6e2c526e46"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectClick"",
                    ""type"": ""Button"",
                    ""id"": ""581d02ac-c4e3-418e-ac16-a6dbc3bbc39e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackClick"",
                    ""type"": ""Button"",
                    ""id"": ""7c78f711-47be-47b3-b3e1-04865a1d14a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DetailsClick"",
                    ""type"": ""Button"",
                    ""id"": ""3347af0d-ef8c-411e-9d54-1c9c10f93e73"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BasicAttackClick"",
                    ""type"": ""Button"",
                    ""id"": ""51f2f3c9-941f-43b6-b626-7404acbbd970"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BasicDefenseClick"",
                    ""type"": ""Button"",
                    ""id"": ""fc5387e7-b010-406f-85a3-2780fd031eef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FirstAbilityClick"",
                    ""type"": ""Button"",
                    ""id"": ""618f08ab-7a07-40cf-a3c8-0f92bedb73d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondAbilityClick"",
                    ""type"": ""Button"",
                    ""id"": ""8b102efc-3ce3-44f2-aa6b-63c50c2f0bcb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThirdAbilityClick"",
                    ""type"": ""Button"",
                    ""id"": ""9dee79f0-db68-4c3e-933b-afcafc5a5a5c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FourthAbilityClick"",
                    ""type"": ""Button"",
                    ""id"": ""3dd55fee-0310-480a-951e-d111f267683f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenMenuClick"",
                    ""type"": ""Button"",
                    ""id"": ""79e89792-4d70-4dc4-8931-4f9cbe20547f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ViewTroopsClick"",
                    ""type"": ""Button"",
                    ""id"": ""b888122d-1bce-4588-b547-98ff38c43f38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenInventoryClick"",
                    ""type"": ""Button"",
                    ""id"": ""7fd84d31-94b6-4e68-bbde-10667712e605"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectNextCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""9d5f88cd-7b60-4de9-bafd-87df0f29f18a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectPreviousCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""ea3b674b-df29-4a25-be2d-2c204c9d6ea3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cheat1"",
                    ""type"": ""Button"",
                    ""id"": ""aa374c6e-812f-4485-a8d7-6d6667728253"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cheat2"",
                    ""type"": ""Button"",
                    ""id"": ""042fa219-57b1-4f92-8d4d-2c163e89d3d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""44e43fc3-222a-44bd-8b0e-66a961cf5a4c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""FirstAbilityClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87633496-25f8-4720-8c9c-acaa5bf5b2e0"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ThirdAbilityClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56e8340e-13c9-40a9-9426-b65baf585e5b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""SecondAbilityClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74675439-f35a-4098-ac29-ae7ea8d87b19"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""FourthAbilityClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""3b93ea8e-603f-47d2-bc6e-9c547f0f2c1c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ArrowMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1b198813-666b-4d08-b856-292c6b5faed1"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ArrowMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8c8a2681-0f38-40d4-990f-d7565f27ff40"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ArrowMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""162aaf32-6412-4446-9745-f0655d815476"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ArrowMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bb5e0e15-f0e0-4a4e-877d-3ef57e507686"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ArrowMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d9818ed2-e762-40ff-9499-74de2acc107e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""BasicAttackClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a837ccc-7b30-462f-8d96-b9ab51ca40b8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""BasicDefenseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a35a97c-9fb4-4c3b-8874-995b1da9764d"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cheat1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0a7cba6-4d94-4fd1-b6eb-3eb8598b6fee"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cheat2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72516af2-132a-4d59-9aec-6a0fc3cda50d"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""OpenMenuClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f63c75b0-dbbd-4513-9380-8f72c451b1fe"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""OpenInventoryClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe2c0d37-b13f-4f2f-8028-26b55420ca74"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""LeftMouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d72a8822-1533-426c-be42-e739aa829a07"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""SelectClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1157a2df-7454-43be-84e8-c17f80af27ba"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""BackClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf6881de-d508-4ff9-b9d6-adbdfc6594bd"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""DetailsClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""126036a9-efdb-47f5-9773-8dfbd5460919"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""SelectNextCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd1a7ce5-3de1-4080-aadf-b80a23bcdec4"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""SelectPreviousCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5405f071-3913-4ae9-9a4f-f2556b969ff8"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ViewTroopsClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Conversation"",
            ""id"": ""bba1ee92-5585-4d47-9802-db9688f45a02"",
            ""actions"": [
                {
                    ""name"": ""ConversationInteract"",
                    ""type"": ""Button"",
                    ""id"": ""727d1062-3fd9-402e-9e81-4c31dc72bd7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9c5db3cf-8bfe-4a22-831e-58d59fc773aa"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ConversationInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46ba40a9-8ea7-49d9-9032-580a98968c6e"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ConversationInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Dashboard"",
            ""id"": ""342600f1-84d1-45cf-b9f5-5092c3c96e5b"",
            ""actions"": [
                {
                    ""name"": ""ArrowMovement"",
                    ""type"": ""Value"",
                    ""id"": ""c5f6c6b2-b7ba-41fa-842c-bd527ef87bc0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OpenDesk"",
                    ""type"": ""Button"",
                    ""id"": ""0e794bfa-e59e-486d-b295-4c0ffb1d2ca3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenArmory"",
                    ""type"": ""Button"",
                    ""id"": ""d61f6162-5931-4dd6-8712-21a44fba2217"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenShop"",
                    ""type"": ""Button"",
                    ""id"": ""252b3569-2181-4715-b632-ec8a46a5e167"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenCamp"",
                    ""type"": ""Button"",
                    ""id"": ""4d73cc88-7be5-4377-bc88-2cfa7dbe75ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenAbilities"",
                    ""type"": ""Button"",
                    ""id"": ""d220e32f-b253-4ff5-a151-a7cc4ab60a40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseCurrentTab"",
                    ""type"": ""Button"",
                    ""id"": ""d4ab2cfa-149d-49d6-8625-2bc505c7c84f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4ba55dd0-4fff-47e6-b23a-42f0be4749cd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ArrowMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6f3c8180-2de6-4b93-adcd-4985a7ed4de2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ArrowMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0c40f68c-3848-4c68-9da2-affedc90d5de"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ArrowMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""26b505d9-c0ff-497b-bf05-dfe064f8bd35"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ArrowMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d20f40a3-4317-4c3a-9d90-667d730270aa"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ArrowMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""72c20cbd-bd46-4f49-b6e9-c7045925af89"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""OpenDesk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d229fedf-8144-4730-b3bf-3f6ff82f1a1c"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenArmory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37cbebb5-9842-4562-9e7b-3fe357c3eea2"",
                    ""path"": ""<Keyboard>/f4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCamp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42ff2eb8-2fd2-4e57-9976-2ae1ee826fbb"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenAbilities"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bb78c5c-9a94-46a4-86dc-b577e47bb602"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenShop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d1ff745-8a7c-40a1-abb4-b303fb285b49"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseCurrentTab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_ArrowMovement = m_Player.FindAction("ArrowMovement", throwIfNotFound: true);
        m_Player_LeftMouseClick = m_Player.FindAction("LeftMouseClick", throwIfNotFound: true);
        m_Player_SelectClick = m_Player.FindAction("SelectClick", throwIfNotFound: true);
        m_Player_BackClick = m_Player.FindAction("BackClick", throwIfNotFound: true);
        m_Player_DetailsClick = m_Player.FindAction("DetailsClick", throwIfNotFound: true);
        m_Player_BasicAttackClick = m_Player.FindAction("BasicAttackClick", throwIfNotFound: true);
        m_Player_BasicDefenseClick = m_Player.FindAction("BasicDefenseClick", throwIfNotFound: true);
        m_Player_FirstAbilityClick = m_Player.FindAction("FirstAbilityClick", throwIfNotFound: true);
        m_Player_SecondAbilityClick = m_Player.FindAction("SecondAbilityClick", throwIfNotFound: true);
        m_Player_ThirdAbilityClick = m_Player.FindAction("ThirdAbilityClick", throwIfNotFound: true);
        m_Player_FourthAbilityClick = m_Player.FindAction("FourthAbilityClick", throwIfNotFound: true);
        m_Player_OpenMenuClick = m_Player.FindAction("OpenMenuClick", throwIfNotFound: true);
        m_Player_ViewTroopsClick = m_Player.FindAction("ViewTroopsClick", throwIfNotFound: true);
        m_Player_OpenInventoryClick = m_Player.FindAction("OpenInventoryClick", throwIfNotFound: true);
        m_Player_SelectNextCharacter = m_Player.FindAction("SelectNextCharacter", throwIfNotFound: true);
        m_Player_SelectPreviousCharacter = m_Player.FindAction("SelectPreviousCharacter", throwIfNotFound: true);
        m_Player_Cheat1 = m_Player.FindAction("Cheat1", throwIfNotFound: true);
        m_Player_Cheat2 = m_Player.FindAction("Cheat2", throwIfNotFound: true);
        // Conversation
        m_Conversation = asset.FindActionMap("Conversation", throwIfNotFound: true);
        m_Conversation_ConversationInteract = m_Conversation.FindAction("ConversationInteract", throwIfNotFound: true);
        // Dashboard
        m_Dashboard = asset.FindActionMap("Dashboard", throwIfNotFound: true);
        m_Dashboard_ArrowMovement = m_Dashboard.FindAction("ArrowMovement", throwIfNotFound: true);
        m_Dashboard_OpenDesk = m_Dashboard.FindAction("OpenDesk", throwIfNotFound: true);
        m_Dashboard_OpenArmory = m_Dashboard.FindAction("OpenArmory", throwIfNotFound: true);
        m_Dashboard_OpenShop = m_Dashboard.FindAction("OpenShop", throwIfNotFound: true);
        m_Dashboard_OpenCamp = m_Dashboard.FindAction("OpenCamp", throwIfNotFound: true);
        m_Dashboard_OpenAbilities = m_Dashboard.FindAction("OpenAbilities", throwIfNotFound: true);
        m_Dashboard_CloseCurrentTab = m_Dashboard.FindAction("CloseCurrentTab", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_ArrowMovement;
    private readonly InputAction m_Player_LeftMouseClick;
    private readonly InputAction m_Player_SelectClick;
    private readonly InputAction m_Player_BackClick;
    private readonly InputAction m_Player_DetailsClick;
    private readonly InputAction m_Player_BasicAttackClick;
    private readonly InputAction m_Player_BasicDefenseClick;
    private readonly InputAction m_Player_FirstAbilityClick;
    private readonly InputAction m_Player_SecondAbilityClick;
    private readonly InputAction m_Player_ThirdAbilityClick;
    private readonly InputAction m_Player_FourthAbilityClick;
    private readonly InputAction m_Player_OpenMenuClick;
    private readonly InputAction m_Player_ViewTroopsClick;
    private readonly InputAction m_Player_OpenInventoryClick;
    private readonly InputAction m_Player_SelectNextCharacter;
    private readonly InputAction m_Player_SelectPreviousCharacter;
    private readonly InputAction m_Player_Cheat1;
    private readonly InputAction m_Player_Cheat2;
    public struct PlayerActions
    {
        private @InputMaster m_Wrapper;
        public PlayerActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @ArrowMovement => m_Wrapper.m_Player_ArrowMovement;
        public InputAction @LeftMouseClick => m_Wrapper.m_Player_LeftMouseClick;
        public InputAction @SelectClick => m_Wrapper.m_Player_SelectClick;
        public InputAction @BackClick => m_Wrapper.m_Player_BackClick;
        public InputAction @DetailsClick => m_Wrapper.m_Player_DetailsClick;
        public InputAction @BasicAttackClick => m_Wrapper.m_Player_BasicAttackClick;
        public InputAction @BasicDefenseClick => m_Wrapper.m_Player_BasicDefenseClick;
        public InputAction @FirstAbilityClick => m_Wrapper.m_Player_FirstAbilityClick;
        public InputAction @SecondAbilityClick => m_Wrapper.m_Player_SecondAbilityClick;
        public InputAction @ThirdAbilityClick => m_Wrapper.m_Player_ThirdAbilityClick;
        public InputAction @FourthAbilityClick => m_Wrapper.m_Player_FourthAbilityClick;
        public InputAction @OpenMenuClick => m_Wrapper.m_Player_OpenMenuClick;
        public InputAction @ViewTroopsClick => m_Wrapper.m_Player_ViewTroopsClick;
        public InputAction @OpenInventoryClick => m_Wrapper.m_Player_OpenInventoryClick;
        public InputAction @SelectNextCharacter => m_Wrapper.m_Player_SelectNextCharacter;
        public InputAction @SelectPreviousCharacter => m_Wrapper.m_Player_SelectPreviousCharacter;
        public InputAction @Cheat1 => m_Wrapper.m_Player_Cheat1;
        public InputAction @Cheat2 => m_Wrapper.m_Player_Cheat2;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @ArrowMovement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnArrowMovement;
                @ArrowMovement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnArrowMovement;
                @ArrowMovement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnArrowMovement;
                @LeftMouseClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftMouseClick;
                @LeftMouseClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftMouseClick;
                @LeftMouseClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftMouseClick;
                @SelectClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectClick;
                @SelectClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectClick;
                @SelectClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectClick;
                @BackClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackClick;
                @BackClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackClick;
                @BackClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackClick;
                @DetailsClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDetailsClick;
                @DetailsClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDetailsClick;
                @DetailsClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDetailsClick;
                @BasicAttackClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBasicAttackClick;
                @BasicAttackClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBasicAttackClick;
                @BasicAttackClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBasicAttackClick;
                @BasicDefenseClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBasicDefenseClick;
                @BasicDefenseClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBasicDefenseClick;
                @BasicDefenseClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBasicDefenseClick;
                @FirstAbilityClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFirstAbilityClick;
                @FirstAbilityClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFirstAbilityClick;
                @FirstAbilityClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFirstAbilityClick;
                @SecondAbilityClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondAbilityClick;
                @SecondAbilityClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondAbilityClick;
                @SecondAbilityClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSecondAbilityClick;
                @ThirdAbilityClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThirdAbilityClick;
                @ThirdAbilityClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThirdAbilityClick;
                @ThirdAbilityClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnThirdAbilityClick;
                @FourthAbilityClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFourthAbilityClick;
                @FourthAbilityClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFourthAbilityClick;
                @FourthAbilityClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFourthAbilityClick;
                @OpenMenuClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOpenMenuClick;
                @OpenMenuClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOpenMenuClick;
                @OpenMenuClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOpenMenuClick;
                @ViewTroopsClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnViewTroopsClick;
                @ViewTroopsClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnViewTroopsClick;
                @ViewTroopsClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnViewTroopsClick;
                @OpenInventoryClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOpenInventoryClick;
                @OpenInventoryClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOpenInventoryClick;
                @OpenInventoryClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOpenInventoryClick;
                @SelectNextCharacter.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectNextCharacter;
                @SelectNextCharacter.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectNextCharacter;
                @SelectNextCharacter.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectNextCharacter;
                @SelectPreviousCharacter.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectPreviousCharacter;
                @SelectPreviousCharacter.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectPreviousCharacter;
                @SelectPreviousCharacter.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSelectPreviousCharacter;
                @Cheat1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCheat1;
                @Cheat1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCheat1;
                @Cheat1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCheat1;
                @Cheat2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCheat2;
                @Cheat2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCheat2;
                @Cheat2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCheat2;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ArrowMovement.started += instance.OnArrowMovement;
                @ArrowMovement.performed += instance.OnArrowMovement;
                @ArrowMovement.canceled += instance.OnArrowMovement;
                @LeftMouseClick.started += instance.OnLeftMouseClick;
                @LeftMouseClick.performed += instance.OnLeftMouseClick;
                @LeftMouseClick.canceled += instance.OnLeftMouseClick;
                @SelectClick.started += instance.OnSelectClick;
                @SelectClick.performed += instance.OnSelectClick;
                @SelectClick.canceled += instance.OnSelectClick;
                @BackClick.started += instance.OnBackClick;
                @BackClick.performed += instance.OnBackClick;
                @BackClick.canceled += instance.OnBackClick;
                @DetailsClick.started += instance.OnDetailsClick;
                @DetailsClick.performed += instance.OnDetailsClick;
                @DetailsClick.canceled += instance.OnDetailsClick;
                @BasicAttackClick.started += instance.OnBasicAttackClick;
                @BasicAttackClick.performed += instance.OnBasicAttackClick;
                @BasicAttackClick.canceled += instance.OnBasicAttackClick;
                @BasicDefenseClick.started += instance.OnBasicDefenseClick;
                @BasicDefenseClick.performed += instance.OnBasicDefenseClick;
                @BasicDefenseClick.canceled += instance.OnBasicDefenseClick;
                @FirstAbilityClick.started += instance.OnFirstAbilityClick;
                @FirstAbilityClick.performed += instance.OnFirstAbilityClick;
                @FirstAbilityClick.canceled += instance.OnFirstAbilityClick;
                @SecondAbilityClick.started += instance.OnSecondAbilityClick;
                @SecondAbilityClick.performed += instance.OnSecondAbilityClick;
                @SecondAbilityClick.canceled += instance.OnSecondAbilityClick;
                @ThirdAbilityClick.started += instance.OnThirdAbilityClick;
                @ThirdAbilityClick.performed += instance.OnThirdAbilityClick;
                @ThirdAbilityClick.canceled += instance.OnThirdAbilityClick;
                @FourthAbilityClick.started += instance.OnFourthAbilityClick;
                @FourthAbilityClick.performed += instance.OnFourthAbilityClick;
                @FourthAbilityClick.canceled += instance.OnFourthAbilityClick;
                @OpenMenuClick.started += instance.OnOpenMenuClick;
                @OpenMenuClick.performed += instance.OnOpenMenuClick;
                @OpenMenuClick.canceled += instance.OnOpenMenuClick;
                @ViewTroopsClick.started += instance.OnViewTroopsClick;
                @ViewTroopsClick.performed += instance.OnViewTroopsClick;
                @ViewTroopsClick.canceled += instance.OnViewTroopsClick;
                @OpenInventoryClick.started += instance.OnOpenInventoryClick;
                @OpenInventoryClick.performed += instance.OnOpenInventoryClick;
                @OpenInventoryClick.canceled += instance.OnOpenInventoryClick;
                @SelectNextCharacter.started += instance.OnSelectNextCharacter;
                @SelectNextCharacter.performed += instance.OnSelectNextCharacter;
                @SelectNextCharacter.canceled += instance.OnSelectNextCharacter;
                @SelectPreviousCharacter.started += instance.OnSelectPreviousCharacter;
                @SelectPreviousCharacter.performed += instance.OnSelectPreviousCharacter;
                @SelectPreviousCharacter.canceled += instance.OnSelectPreviousCharacter;
                @Cheat1.started += instance.OnCheat1;
                @Cheat1.performed += instance.OnCheat1;
                @Cheat1.canceled += instance.OnCheat1;
                @Cheat2.started += instance.OnCheat2;
                @Cheat2.performed += instance.OnCheat2;
                @Cheat2.canceled += instance.OnCheat2;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Conversation
    private readonly InputActionMap m_Conversation;
    private IConversationActions m_ConversationActionsCallbackInterface;
    private readonly InputAction m_Conversation_ConversationInteract;
    public struct ConversationActions
    {
        private @InputMaster m_Wrapper;
        public ConversationActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @ConversationInteract => m_Wrapper.m_Conversation_ConversationInteract;
        public InputActionMap Get() { return m_Wrapper.m_Conversation; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ConversationActions set) { return set.Get(); }
        public void SetCallbacks(IConversationActions instance)
        {
            if (m_Wrapper.m_ConversationActionsCallbackInterface != null)
            {
                @ConversationInteract.started -= m_Wrapper.m_ConversationActionsCallbackInterface.OnConversationInteract;
                @ConversationInteract.performed -= m_Wrapper.m_ConversationActionsCallbackInterface.OnConversationInteract;
                @ConversationInteract.canceled -= m_Wrapper.m_ConversationActionsCallbackInterface.OnConversationInteract;
            }
            m_Wrapper.m_ConversationActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ConversationInteract.started += instance.OnConversationInteract;
                @ConversationInteract.performed += instance.OnConversationInteract;
                @ConversationInteract.canceled += instance.OnConversationInteract;
            }
        }
    }
    public ConversationActions @Conversation => new ConversationActions(this);

    // Dashboard
    private readonly InputActionMap m_Dashboard;
    private IDashboardActions m_DashboardActionsCallbackInterface;
    private readonly InputAction m_Dashboard_ArrowMovement;
    private readonly InputAction m_Dashboard_OpenDesk;
    private readonly InputAction m_Dashboard_OpenArmory;
    private readonly InputAction m_Dashboard_OpenShop;
    private readonly InputAction m_Dashboard_OpenCamp;
    private readonly InputAction m_Dashboard_OpenAbilities;
    private readonly InputAction m_Dashboard_CloseCurrentTab;
    public struct DashboardActions
    {
        private @InputMaster m_Wrapper;
        public DashboardActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @ArrowMovement => m_Wrapper.m_Dashboard_ArrowMovement;
        public InputAction @OpenDesk => m_Wrapper.m_Dashboard_OpenDesk;
        public InputAction @OpenArmory => m_Wrapper.m_Dashboard_OpenArmory;
        public InputAction @OpenShop => m_Wrapper.m_Dashboard_OpenShop;
        public InputAction @OpenCamp => m_Wrapper.m_Dashboard_OpenCamp;
        public InputAction @OpenAbilities => m_Wrapper.m_Dashboard_OpenAbilities;
        public InputAction @CloseCurrentTab => m_Wrapper.m_Dashboard_CloseCurrentTab;
        public InputActionMap Get() { return m_Wrapper.m_Dashboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DashboardActions set) { return set.Get(); }
        public void SetCallbacks(IDashboardActions instance)
        {
            if (m_Wrapper.m_DashboardActionsCallbackInterface != null)
            {
                @ArrowMovement.started -= m_Wrapper.m_DashboardActionsCallbackInterface.OnArrowMovement;
                @ArrowMovement.performed -= m_Wrapper.m_DashboardActionsCallbackInterface.OnArrowMovement;
                @ArrowMovement.canceled -= m_Wrapper.m_DashboardActionsCallbackInterface.OnArrowMovement;
                @OpenDesk.started -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenDesk;
                @OpenDesk.performed -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenDesk;
                @OpenDesk.canceled -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenDesk;
                @OpenArmory.started -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenArmory;
                @OpenArmory.performed -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenArmory;
                @OpenArmory.canceled -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenArmory;
                @OpenShop.started -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenShop;
                @OpenShop.performed -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenShop;
                @OpenShop.canceled -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenShop;
                @OpenCamp.started -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenCamp;
                @OpenCamp.performed -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenCamp;
                @OpenCamp.canceled -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenCamp;
                @OpenAbilities.started -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenAbilities;
                @OpenAbilities.performed -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenAbilities;
                @OpenAbilities.canceled -= m_Wrapper.m_DashboardActionsCallbackInterface.OnOpenAbilities;
                @CloseCurrentTab.started -= m_Wrapper.m_DashboardActionsCallbackInterface.OnCloseCurrentTab;
                @CloseCurrentTab.performed -= m_Wrapper.m_DashboardActionsCallbackInterface.OnCloseCurrentTab;
                @CloseCurrentTab.canceled -= m_Wrapper.m_DashboardActionsCallbackInterface.OnCloseCurrentTab;
            }
            m_Wrapper.m_DashboardActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ArrowMovement.started += instance.OnArrowMovement;
                @ArrowMovement.performed += instance.OnArrowMovement;
                @ArrowMovement.canceled += instance.OnArrowMovement;
                @OpenDesk.started += instance.OnOpenDesk;
                @OpenDesk.performed += instance.OnOpenDesk;
                @OpenDesk.canceled += instance.OnOpenDesk;
                @OpenArmory.started += instance.OnOpenArmory;
                @OpenArmory.performed += instance.OnOpenArmory;
                @OpenArmory.canceled += instance.OnOpenArmory;
                @OpenShop.started += instance.OnOpenShop;
                @OpenShop.performed += instance.OnOpenShop;
                @OpenShop.canceled += instance.OnOpenShop;
                @OpenCamp.started += instance.OnOpenCamp;
                @OpenCamp.performed += instance.OnOpenCamp;
                @OpenCamp.canceled += instance.OnOpenCamp;
                @OpenAbilities.started += instance.OnOpenAbilities;
                @OpenAbilities.performed += instance.OnOpenAbilities;
                @OpenAbilities.canceled += instance.OnOpenAbilities;
                @CloseCurrentTab.started += instance.OnCloseCurrentTab;
                @CloseCurrentTab.performed += instance.OnCloseCurrentTab;
                @CloseCurrentTab.canceled += instance.OnCloseCurrentTab;
            }
        }
    }
    public DashboardActions @Dashboard => new DashboardActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnArrowMovement(InputAction.CallbackContext context);
        void OnLeftMouseClick(InputAction.CallbackContext context);
        void OnSelectClick(InputAction.CallbackContext context);
        void OnBackClick(InputAction.CallbackContext context);
        void OnDetailsClick(InputAction.CallbackContext context);
        void OnBasicAttackClick(InputAction.CallbackContext context);
        void OnBasicDefenseClick(InputAction.CallbackContext context);
        void OnFirstAbilityClick(InputAction.CallbackContext context);
        void OnSecondAbilityClick(InputAction.CallbackContext context);
        void OnThirdAbilityClick(InputAction.CallbackContext context);
        void OnFourthAbilityClick(InputAction.CallbackContext context);
        void OnOpenMenuClick(InputAction.CallbackContext context);
        void OnViewTroopsClick(InputAction.CallbackContext context);
        void OnOpenInventoryClick(InputAction.CallbackContext context);
        void OnSelectNextCharacter(InputAction.CallbackContext context);
        void OnSelectPreviousCharacter(InputAction.CallbackContext context);
        void OnCheat1(InputAction.CallbackContext context);
        void OnCheat2(InputAction.CallbackContext context);
    }
    public interface IConversationActions
    {
        void OnConversationInteract(InputAction.CallbackContext context);
    }
    public interface IDashboardActions
    {
        void OnArrowMovement(InputAction.CallbackContext context);
        void OnOpenDesk(InputAction.CallbackContext context);
        void OnOpenArmory(InputAction.CallbackContext context);
        void OnOpenShop(InputAction.CallbackContext context);
        void OnOpenCamp(InputAction.CallbackContext context);
        void OnOpenAbilities(InputAction.CallbackContext context);
        void OnCloseCurrentTab(InputAction.CallbackContext context);
    }
}
